[package]
name = "bytes_base64_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet = "0.8.0"
base64 = "0.21.5"
primitive-types = "0.12.2"
